### ISSUE TITLE
Когда я пытаюсь вызвать SDK.Pay() на IOS

### ISSUE THREAD

**Issue by VKabz** [itrcz/react-native-asdk-tinkoff#1]
Thread 1: "[<UITableViewCell 0x105a80d50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key activityIndicator."

**Comment by itrcz** [comment]
[fix](https://github.com/itrcz/react-native-asdk-tinkoff/commit/fd08f29edad1eebc02db0ff3d8ffd1a1a36b801c)
